#!/usr/bin/env python3
"""
Generate 16x16 Korean bitmap font data for Rust const arrays.
Uses macOS "Apple SD Gothic Neo" font via Pillow.

Usage:
    pip install Pillow
    python scripts/gen_korean_font.py
"""

from PIL import Image, ImageDraw, ImageFont
import sys

# Characters needed (42 total)
CHARS = [
    # 요일 (7)
    '월', '화', '수', '목', '금', '토', '일',
    # 날씨 (15)
    '맑', '음', '흐', '림', '구', '름', '비', '눈', '안', '개', '박', '무', '연', '뇌', '우',
    # 라벨 (2)
    '습', '도',
    # 기타 (2)
    '이', '슬',
    # Menu glyphs (16)
    '설', '정', '언', '시', '간', '대', '온', '한', '국', '영', '주', '기', '반', '전', '분', '어',
]

SIZE = 16  # 16x16 pixel glyphs

# macOS Korean fonts to try (in order of preference)
FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/AppleSDGothicNeo.ttc",
    "/System/Library/Fonts/AppleSDGothicNeo.ttc",
    "/Library/Fonts/AppleSDGothicNeo.ttc",
    "/System/Library/Fonts/Supplemental/AppleGothic.ttf",
    "/System/Library/Fonts/AppleGothic.ttf",
]


def find_font(size):
    for path in FONT_CANDIDATES:
        try:
            font = ImageFont.truetype(path, size)
            return font
        except (OSError, IOError):
            continue
    print("ERROR: No Korean font found. Tried:", file=sys.stderr)
    for p in FONT_CANDIDATES:
        print(f"  {p}", file=sys.stderr)
    sys.exit(1)


def render_char(ch, font):
    """Render a single character to a 16x16 1-bit bitmap, returns [u8; 32]."""
    img = Image.new('1', (SIZE, SIZE), color=0)  # black background
    draw = ImageDraw.Draw(img)

    # Get bounding box to center the character
    bbox = font.getbbox(ch)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]

    # Center in 16x16
    x = (SIZE - w) // 2 - bbox[0]
    y = (SIZE - h) // 2 - bbox[1]

    draw.text((x, y), ch, fill=1, font=font)

    # Convert to bytes: 2 bytes per row, MSB first
    data = []
    for row in range(SIZE):
        byte_hi = 0
        byte_lo = 0
        for col in range(8):
            if img.getpixel((col, row)):
                byte_hi |= (0x80 >> col)
        for col in range(8, SIZE):
            if img.getpixel((col, row)):
                byte_lo |= (0x80 >> (col - 8))
        data.append(byte_hi)
        data.append(byte_lo)

    return data


def main():
    # Try font size 14 first (fits well in 16x16 grid)
    font = find_font(14)
    print(f"// Auto-generated by scripts/gen_korean_font.py")
    print(f"// Font: Apple SD Gothic Neo, rendered at 14px into 16x16 grid")
    print(f"// {len(CHARS)} characters, {len(CHARS) * 32} bytes total")
    print()

    # Print preview to stderr
    for ch in CHARS:
        bitmap = render_char(ch, font)
        print(f"// Preview: '{ch}'", file=sys.stderr)
        for row in range(SIZE):
            hi = bitmap[row * 2]
            lo = bitmap[row * 2 + 1]
            line = ""
            for bit in range(8):
                line += "##" if (hi & (0x80 >> bit)) else "  "
            for bit in range(8):
                line += "##" if (lo & (0x80 >> bit)) else "  "
            print(f"// {line}", file=sys.stderr)
        print(file=sys.stderr)

    # Output Rust code
    print("pub const GLYPH_DATA: &[(char, [u8; 32])] = &[")
    for ch in CHARS:
        bitmap = render_char(ch, font)
        hex_str = ", ".join(f"0x{b:02X}" for b in bitmap)
        print(f"    ('{ch}', [{hex_str}]),")
    print("];")


if __name__ == '__main__':
    main()
